resources:
  - name: script_gh
    type: GitRepo
    configuration:
      path: deepikasl/sample-script
      gitProvider: deepikaGithub
      branches:
        include: ^{{gitBranch}}$

pipelines:
  - name: sample_test_jenkins
    steps:
      - name: bash
        type: Bash
        execution:
          onExecute:
            - echo "Executing step_A"
            - blah
            - printenv
      - name: jenkins_test
        type: Jenkins
        configuration:
          inputSteps:
            - name: bash
              status:
                - success
          jenkinsJobName: testPipeline
          integrations:
            - name: deepikaJenkins
      
      - name: step_A
        type: Bash
        configuration:
          inputSteps:
            - name: jenkins
              status:
                - success
        execution:
          onExecute:
            - echo "Executing step_A"
            - printenv
  - name: simple_jenkins_demo
    steps:
      - name: jenkins
        type: Jenkins
        configuration:
          inputResources:
            - name: script_gh
          jenkinsJobName: testPipeline
          integrations:
            - name: deepikaJenkins
      
      - name: step_A
        type: Bash
        configuration:
          inputSteps:
            - name: jenkins
              status:
                - success
        execution:
          onExecute:
            - echo "Executing step_A"
            - printenv
     
      - name: simple_conditional_B
        type: Bash
        configuration:
          inputSteps:
            - name: jenkins
              status:
                - failure
                - error
        execution:
          onExecute:
            - echo "Executing simple_conditional_B"
            - printenv
            
